### ISSUE TITLE
Way to use only part of the background for harmonization. Transparent images harmonization

### ISSUE THREAD

**Issue by Vozf** [saic-vul/image_harmonization#8]
If we use 2 transparent images and try to harmonize them with each other we will have to fill the transparent regions with some color. If we use black color the harmonized image will become darker because of that. Is there a way to select only part of the background for harmonization(non-transparent part of the transparent image)? Like additional mask for instance. If not is there a preffered way to fill the transparent regions when harmonizing transparent images?

**Comment by polyhex-sqr** [comment]
Hi @Vozf 

> Is there a way to select only part of the background for harmonization(non-transparent part of the transparent image)? Like additional mask for instance.
Our current model does not support such an input, however you can try to train your own from scratch. My guess is you will have to augment training data with partly transparent background and add the background mask to the network input along with an image and an object mask.

> is there a preffered way to fill the transparent regions when harmonizing transparent images?
I would try filling the transparent background areas with random values first, so that the filled areas have neutral lighting and colours

**Comment by Vozf** [comment]
Thanks for the response
